### ISSUE TITLE
".Values.volumeMounts" not used inside Daemonset/Deployment Chart Templates

### ISSUE THREAD

**Issue by johanneskant-tomtom** [scalyr/helm-scalyr#25]
Hello everyone,

first, I want to thank you for all the time you already spent into this project!

Unfortunately, there seems to be a small bug inside the `volumeMounts` section of the [daemonset.yaml](https://github.com/scalyr/helm-scalyr/blob/main/charts/scalyr-agent/templates/daemonset.yaml) and [deployment.yaml](https://github.com/scalyr/helm-scalyr/blob/main/charts/scalyr-agent/templates/deployment.yaml) chart templates.

For some reason `.Values.volumes` is used there instead of `.Values.volumeMounts` what makes it currently impossible, to add volume (mounts) via a `values.yaml` file.

It would be great, If this issue could be fixed some day.

Many thanks in advance!
Johannes

**Comment by Kami** [comment]
Thanks and a good catch.

I assume our end to end tests didn't catch that since we don't have a scenario in the test where ``.Values.volumeMounts`` is populated.

Will look into adding such test case.
