### ISSUE TITLE
Add the ability to configure PriorityClass

### ISSUE THREAD

**Issue by justinb-shipt** [scalyr/helm-scalyr#41]
scalyr-agent gets a PriorityClass of default. When there's a cluster upgrade, there's a chance that the agent might not get scheduled on a Node because of all the resources already accounted for. Then the Pod is left in a pending state and you won't see any logs from Pods on that Node. Then manual intervention is needed. If scalyr-agent can be given a higher priority, it can be scheduled first and one will hopefully not run into this issue.

**Comment by Kami** [comment]
Merged via #42. Thanks.
