### ISSUE TITLE
Latest agent image 2.2.3 does not work with EKS

### ISSUE THREAD

**Issue by cpetestewart** [scalyr/helm-scalyr#62]
I recently set about upgrading our old scalyr chart which we had manually downloaded and modified because at the time serviceAccount annotations were not supported. However, attempting to use the latest chart with the 2.2.3 image gives me this error:

  Warning  FailedCreate      2s                 daemonset-controller  Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.adm
ission.doit-intl.com": failed to call webhook: an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\
"uid\":\"c5b44feb-95e6-46a2-b264-490e01c7e805\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot download manifest for image: Get \\\"https://index.docker.io/v2/scalyr/scalyr-k8s-agent/manifests/2.2.3\\\": http: non-successful response (status=404 body=\\\"{\\\\\\\"errors\\\\\\\":[{\\\\\\\"code\\\\\\\":\\\\\\\"MANIFEST_UNKNOWN\\\\\\\",\\\\\\\"message\\\\\\\":\\\\\\\"OCI index found, but accept header does not support OCI indexes\\\\\\\"}]}\\\\n\\\")\"}}}") has prevented the request from succeeding

If I change my values file to set image.tag to the older version of 2.1.3, the problem goes away. We use kube-secrets-init to allow use of parameter store for secret values, so it is essential they work together (I have a second problem with this, but I will file this under a different issue).

**Comment by cpetestewart** [comment]
My apologies. I traced the issue to using an outdated image for kube-secrets-init. With the latest image, this issue is resolved. I still have the other issue I entered today that is blocking me.

**Comment by tomaz-s1** [comment]
@cpetestewart #64 has been merged and a new chart version with those change (v0.2.34) is now available - https://scalyr.github.io/helm-scalyr/.
